default : fast

slow :
	scalac -nowarn -d target/scala-2.10/classes src/main/scala/graphprog/{*.scala,*/*.scala}

fast :
	fsc -nowarn -d target/scala-2.10/classes src/main/scala/graphprog/{*.scala,*/*.scala}
